import { AuthorData, BookData } from "./types";

export const authors: AuthorData[] = [
  {
    name: "J.K. Rowling",
    nationality: "British",
    birthYear: 1965,
    notableWorks: ["Harry Potter series", "The Casual Vacancy"],
  },
  {
    name: "George Orwell",
    nationality: "British",
    birthYear: 1903,
    notableWorks: ["1984", "Animal Farm"],
  },
  {
    name: "J.R.R. Tolkien",
    nationality: "British",
    birthYear: 1892,
    notableWorks: ["The Lord of the Rings", "The Hobbit"],
  },
  {
    name: "Harper Lee",
    nationality: "American",
    birthYear: 1926,
    notableWorks: ["To Kill a Mockingbird"],
  },
  {
    name: "Frank Herbert",
    nationality: "American",
    birthYear: 1920,
    notableWorks: ["Dune series"],
  },
  {
    name: "Brandon Sanderson",
    nationality: "American",
    birthYear: 1975,
    notableWorks: [
      "Mistborn series",
      "Stormlight Archive",
      "The Wheel of Time",
    ],
  },
  {
    name: "Andrzej Sapkowski",
    nationality: "Polish",
    birthYear: 1948,
    notableWorks: ["The Witcher series", "Hussite Trilogy"],
  },
  {
    name: "Patrick Rothfuss",
    nationality: "American",
    birthYear: 1973,
    notableWorks: ["The Kingkiller Chronicle"],
  },
  {
    name: "Ursula K. Le Guin",
    nationality: "American",
    birthYear: 1929,
    notableWorks: ["Earthsea series", "The Left Hand of Darkness"],
  },
  {
    name: "Robin Hobb",
    nationality: "American",
    birthYear: 1952,
    notableWorks: ["Farseer Trilogy", "Liveship Traders"],
  },
];

export const books: BookData[] = [
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    publicationYear: 1997,
    genre: "Fantasy",
    pageCount: 223,
    isbn: "9780747532699",
    rating: 4.8,
    synopsis: "A young boy discovers his magical heritage",
  },
  {
    title: "1984",
    author: "George Orwell",
    publicationYear: 1949,
    genre: "Dystopian",
    pageCount: 328,
    isbn: "9780451524935",
    rating: 4.7,
    synopsis: "A grim vision of a totalitarian future society",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publicationYear: 1937,
    genre: "Fantasy",
    pageCount: 310,
    isbn: "9780261102217",
    rating: 4.9,
    synopsis: "A hobbit's adventure to reclaim a dragon-guarded treasure",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publicationYear: 1960,
    genre: "Southern Gothic",
    pageCount: 281,
    isbn: "9780060935467",
    rating: 4.8,
    synopsis: "A story of racial injustice in the American South",
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    publicationYear: 1965,
    genre: "Science Fiction",
    pageCount: 412,
    isbn: "9780441172719",
    rating: 4.6,
    synopsis:
      "A political struggle over control of desert planet's spice resource",
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    publicationYear: 2008,
    genre: "Dystopian",
    pageCount: 374,
    isbn: "9780439023481",
    rating: 4.3,
    synopsis: "Teenagers forced to fight in a televised death match",
  },
  {
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    publicationYear: 2006,
    genre: "Fantasy",
    pageCount: 541,
    isbn: "9780765311788",
    rating: 4.5,
    synopsis:
      "A street urchin joins a crew of thieves to overthrow a god-like ruler",
  },
  {
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    publicationYear: 2010,
    genre: "Epic Fantasy",
    pageCount: 1007,
    isbn: "9780765326355",
    rating: 4.7,
    synopsis:
      "A divided kingdom struggles against mysterious forces of destruction",
  },
  {
    title: "The Last Wish",
    author: "Andrzej Sapkowski",
    publicationYear: 1993,
    genre: "Fantasy",
    pageCount: 280,
    isbn: "9780316029186",
    rating: 4.3,
    synopsis:
      "Short stories introducing Geralt of Rivia, a monster-hunting witcher",
  },
  {
    title: "Blood of Elves",
    author: "Andrzej Sapkowski",
    publicationYear: 1994,
    genre: "Fantasy",
    pageCount: 320,
    isbn: "9780316029193",
    rating: 4.4,
    synopsis: "Geralt protects a young girl with mysterious powers",
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    publicationYear: 2007,
    genre: "Fantasy",
    pageCount: 662,
    isbn: "9780756404741",
    rating: 4.6,
    synopsis: "A legendary wizard recounts his tumultuous life story",
  },
  {
    title: "A Wizard of Earthsea",
    author: "Ursula K. Le Guin",
    publicationYear: 1968,
    genre: "Fantasy",
    pageCount: 183,
    isbn: "9780553383041",
    rating: 4.3,
    synopsis: "A young wizard's journey of self-discovery and balance",
  },
  {
    title: "Assassin's Apprentice",
    author: "Robin Hobb",
    publicationYear: 1995,
    genre: "Fantasy",
    pageCount: 435,
    isbn: "9780553573398",
    rating: 4.2,
    synopsis: "A royal bastard trains as an assassin in a dangerous court",
  },
  {
    title: "The Eye of the World",
    author: "Robert Jordan",
    publicationYear: 1990,
    genre: "Epic Fantasy",
    pageCount: 814,
    isbn: "9780812511819",
    rating: 4.5,
    synopsis: "Farm boys embark on a journey that will change the world's fate",
  },
];
